### ISSUE TITLE
Trigger cert movement

### ISSUE THREAD

**Issue by BeauAgst** [Magisk-Modules-Repo/movecert#7] opened 2020-04-30 14:25 UTC
Hi, I've installed this module. 

I've added a cert, and I can see it in my _User Credentials_ 
What do I need to do to trigger it copying into my _Trusted Credentials_? I don't see it in the list.

Thanks,

**Comment by Hill-98** [comment] 2020-04-30 15:10
Just restart the system and the user certificate should appear in the system certificate list and disappear in the user certificate list.

If the user certificate does not appear in the system certificate list after restarting the system, and disappears from the user certificate list, it may be an error caused by the SELinux context. This error has been fixed in # 7, waiting for the new version to be released.

**Closed** 2020-05-03 01:02 UTC
